server:
  port: 9000

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/diogoaltoe/spring-cloud-microservices
          searchPaths: config-data
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: /home/diogoaltoe/appservers/apache-tomcat-9.0.4/webapps/config-data/          

---
security:
  user:
    name: config
    password: $2a$10$r0RFDmpneBVryx.ihHK9gu6FFJQi4nTxQUqzdSTvrPpaKZMxigqpy
    role: SYSTEM